magictable.info/site_config.json is invalid
magictable.info/site_config.json is invalid
magictable.info/site_config.json is invalid
Expecting property name enclosed in double quotes: line 15 column 1 (char 339)
Expecting property name enclosed in double quotes: line 15 column 1 (char 339)
Expecting property name enclosed in double quotes: line 15 column 1 (char 339)
Document Insert Error
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 423, in make_records
    doc.insert(ignore_permissions=True, ignore_if_duplicate=True)
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/fiscal_year/fiscal_year.py", line 33, in validate
    self.validate_dates()
  File "apps/erpnext/erpnext/accounts/doctype/fiscal_year/fiscal_year.py", line 64, in validate_dates
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.InvalidDates: Fiscal Year End Date should be one year after Fiscal Year Start Date

Document Insert Error
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/page/setup_wizard/setup_wizard.py", line 423, in make_records
    doc.insert(ignore_permissions=True, ignore_if_duplicate=True)
  File "apps/frappe/frappe/model/document.py", line 286, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 496, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 166, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 201, in set_name_from_naming_options
    frappe.throw(_("{0} is required").format(doc.meta.get_label(fieldname)))
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Company is required

Updating Dashboard for frappe
Updating Dashboard for erpnext
Updating Dashboard for hrms
